### ISSUE TITLE
Give me my rights

### ISSUE THREAD

**Issue by MTiberiu** [codrineugeniu/git-workshop-fe8#1]
# Where are my rights?
It looks like you don't have write access to codrineugeniu/git-workshop-fe8
If you should, please check with a repository administrator.
![error](https://user-images.githubusercontent.com/45216268/114586900-cdae3500-9c8d-11eb-8eda-235a8b0f827e.png)

**Comment by codrineugeniu** [comment]
:) Direct writes in the repo are blocked by default, feel free to create a pull request instead.

**Comment by MTiberiu** [comment]
Thanks for the direction, I gained a lot of time following the directions given.

**Comment by MTiberiu** [comment]
> :) Direct writes in the repo are blocked by default, feel free to create a pull request instead.

It's seems I can not go further because the repository dosn't have git content 
`The repository exists, but it contains no Git content.
Empty repository cannot be forked`

**Comment by codrineugeniu** [comment]
Turns out an empty repo is a Schrodinger moment, it exists but it cannot be forked :).
I have pushed the files from the workshop, closing this now! 👍
